//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemID { get; set; }
        public int ItemQty { get; set; }
        public string ItemCat { get; set; }
    }
}
