//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Email { get; set; }
        public int OrderID { get; set; }
        public int ItemID { get; set; }
    
        public virtual User User { get; set; }
    }
}
